export const ukStocks = [
  // ============================================
  // FTSE 100 - 51 Large-Cap Stocks
  // ============================================
  { symbol: "BARC.L", name: "Barclays PLC" },
  { symbol: "BP.L", name: "BP PLC" },
  { symbol: "HSBA.L", name: "HSBC Holdings PLC" },
  { symbol: "LLOY.L", name: "Lloyds Banking Group PLC" },
  { symbol: "VOD.L", name: "Vodafone Group PLC" },
  { symbol: "SHEL.L", name: "Shell PLC" },
  { symbol: "GSK.L", name: "GSK PLC" },
  { symbol: "AZN.L", name: "AstraZeneca PLC" },
  { symbol: "DGE.L", name: "Diageo PLC" },
  { symbol: "TSCO.L", name: "Tesco PLC" },
  { symbol: "RIO.L", name: "Rio Tinto PLC" },
  { symbol: "BHP.L", name: "BHP Group Limited" },
  { symbol: "ULVR.L", name: "Unilever PLC" },
  { symbol: "REL.L", name: "RELX PLC" },
  { symbol: "NG.L", name: "National Grid PLC" },
  { symbol: "BATS.L", name: "British American Tobacco PLC" },
  { symbol: "RKT.L", name: "Reckitt Benckiser Group PLC" },
  { symbol: "PRU.L", name: "Prudential PLC" },
  { symbol: "CRH.L", name: "CRH PLC" },
  { symbol: "IMB.L", name: "Imperial Brands PLC" },
  { symbol: "AAL.L", name: "Anglo American PLC" },
  { symbol: "LSEG.L", name: "London Stock Exchange Group PLC" },
  { symbol: "AV.L", name: "Aviva PLC" },
  { symbol: "STAN.L", name: "Standard Chartered PLC" },
  { symbol: "BT-A.L", name: "BT Group PLC" },
  { symbol: "LAND.L", name: "Land Securities Group PLC" },
  { symbol: "SSE.L", name: "SSE PLC" },
  { symbol: "GLEN.L", name: "Glencore PLC" },
  { symbol: "NWG.L", name: "NatWest Group PLC" },
  { symbol: "MKS.L", name: "Marks & Spencer Group PLC" },
  { symbol: "III.L", name: "3i Group PLC" },
  { symbol: "BNZL.L", name: "Bunzl PLC" },
  { symbol: "SGE.L", name: "Sage Group PLC" },
  { symbol: "RMV.L", name: "Rightmove PLC" },
  { symbol: "EXPN.L", name: "Experian PLC" },
  { symbol: "WTB.L", name: "Whitbread PLC" },
  { symbol: "PSN.L", name: "Persimmon PLC" },
  { symbol: "BRBY.L", name: "Burberry Group PLC" },
  { symbol: "ABF.L", name: "Associated British Foods PLC" },
  { symbol: "SMDS.L", name: "DS Smith PLC" },
  { symbol: "CPG.L", name: "Compass Group PLC" },
  { symbol: "INF.L", name: "Informa PLC" },
  { symbol: "IHG.L", name: "InterContinental Hotels Group PLC" },
  { symbol: "OCDO.L", name: "Ocado Group PLC" },
  { symbol: "AUTO.L", name: "Auto Trader Group PLC" },
  { symbol: "SBRY.L", name: "Sainsbury (J) PLC" },
  { symbol: "WPP.L", name: "WPP PLC" },
  { symbol: "PSON.L", name: "Pearson PLC" },
  { symbol: "RR.L", name: "Rolls-Royce Holdings PLC" },
  { symbol: "BA.L", name: "BAE Systems PLC" },
  { symbol: "JD.L", name: "JD Sports Fashion plc" },
  { symbol: "CTEC.L", name: "ConvaTec Group PLC" },
  
  // ============================================
  // FTSE 250 - 27 Mid-Cap Stocks
  // ============================================
  { symbol: "FRAS.L", name: "Frasers Group PLC" },
  { symbol: "MGNS.L", name: "Morgan Sindall Group PLC" },
  { symbol: "ASHM.L", name: "Ashmore Group PLC" },
  { symbol: "DOM.L", name: "Domino's Pizza Group PLC" },
  { symbol: "JDW.L", name: "Wetherspoon (J D) PLC" },
  { symbol: "MNG.L", name: "M&G PLC" },
  { symbol: "PETS.L", name: "Pets at Home Group PLC" },
  { symbol: "TATE.L", name: "Tate & Lyle PLC" },
  { symbol: "IMI.L", name: "IMI PLC" },
  { symbol: "MRW.L", name: "Morrison (Wm) Supermarkets PLC" },
  { symbol: "SMWH.L", name: "WH Smith PLC" },
  { symbol: "HLMA.L", name: "Halma PLC" },
  { symbol: "CTY.L", name: "City of London Investment Group PLC" },
  { symbol: "CWK.L", name: "Cranswick PLC" },
  { symbol: "TW.L", name: "Taylor Wimpey PLC" },
  { symbol: "MNDI.L", name: "Mondi PLC" },
  { symbol: "SPX.L", name: "Spirax-Sarco Engineering PLC" },
  { symbol: "RMG.L", name: "Royal Mail PLC" },
  { symbol: "WEIR.L", name: "Weir Group PLC" },
  { symbol: "DLG.L", name: "Direct Line Insurance Group PLC" },
  { symbol: "RDW.L", name: "Redrow PLC" },
  { symbol: "JMAT.L", name: "Johnson Matthey PLC" },
  { symbol: "SDR.L", name: "Schroders PLC" },
  { symbol: "RSW.L", name: "Renishaw PLC" },
  { symbol: "SN.L", name: "Smith & Nephew PLC" },
  { symbol: "TEP.L", name: "Telecom Plus" },
  { symbol: "MEGP.L", name: "ME Group International PLC" },
  
  // ============================================
  // AIM & Small-Cap - 25 Growth Stocks
  // ============================================
  { symbol: "ASC.L", name: "ASOS PLC" },
  { symbol: "DRX.L", name: "Drax Group PLC" },
  { symbol: "MOON.L", name: "Moonpig Group PLC" },
  { symbol: "FDM.L", name: "FDM Group Holdings PLC" },
  { symbol: "THG.L", name: "THG PLC" },
  { symbol: "SHOE.L", name: "Shoe Zone PLC" },
  { symbol: "FEV.L", name: "Fever-Tree Drinks PLC" },
  { symbol: "CBUY.L", name: "Computacenter PLC" },
  { symbol: "JLP.L", name: "Jubilee Metals Group PLC" },
  { symbol: "MGAM.L", name: "Morgan Advanced Materials PLC" },
  { symbol: "PAY.L", name: "PayPoint PLC" },
  { symbol: "UTG.L", name: "Unite Group PLC" },
  { symbol: "GOG.L", name: "Go-Ahead Group PLC" },
  { symbol: "TALK.L", name: "TalkTalk Telecom Group PLC" },
  { symbol: "MTO.L", name: "Mitie Group PLC" },
  { symbol: "HWDN.L", name: "Howden Joinery Group PLC" },
  { symbol: "TPX.L", name: "Topps Tiles PLC" },
  { symbol: "MAB.L", name: "Mitchells & Butlers PLC" },
  { symbol: "HSX.L", name: "Hiscox Ltd" },
  { symbol: "DEB.L", name: "Debenhams PLC" },
  { symbol: "SPIR.L", name: "Spire Healthcare Group PLC" },
  { symbol: "RWS.L", name: "RWS Holdings PLC" },
  { symbol: "POLY.L", name: "Polymetal International PLC" },
  { symbol: "CCH.L", name: "Coca-Cola HBC AG" },
  { symbol: "SXS.L", name: "Spectris PLC" },
];
