export const usStocks = [
  // Tech Giants (FAANG+)
  { symbol: "AAPL", name: "Apple Inc." },
  { symbol: "MSFT", name: "Microsoft Corporation" },
  { symbol: "GOOGL", name: "Alphabet Inc. Class A" },
  { symbol: "GOOG", name: "Alphabet Inc. Class C" },
  { symbol: "AMZN", name: "Amazon.com Inc." },
  { symbol: "META", name: "Meta Platforms Inc." },
  { symbol: "TSLA", name: "Tesla Inc." },
  { symbol: "NVDA", name: "NVIDIA Corporation" },
  { symbol: "NFLX", name: "Netflix Inc." },
  
  // Major Tech
  { symbol: "AVGO", name: "Broadcom Inc." },
  { symbol: "ORCL", name: "Oracle Corporation" },
  { symbol: "CSCO", name: "Cisco Systems Inc." },
  { symbol: "ADBE", name: "Adobe Inc." },
  { symbol: "CRM", name: "Salesforce Inc." },
  { symbol: "INTC", name: "Intel Corporation" },
  { symbol: "AMD", name: "Advanced Micro Devices Inc." },
  { symbol: "QCOM", name: "QUALCOMM Incorporated" },
  { symbol: "IBM", name: "International Business Machines" },
  { symbol: "NOW", name: "ServiceNow Inc." },
  { symbol: "INTU", name: "Intuit Inc." },
  { symbol: "AMAT", name: "Applied Materials Inc." },
  { symbol: "LRCX", name: "Lam Research Corporation" },
  { symbol: "KLAC", name: "KLA Corporation" },
  { symbol: "SNPS", name: "Synopsys Inc." },
  { symbol: "CDNS", name: "Cadence Design Systems" },
  { symbol: "PANW", name: "Palo Alto Networks Inc." },
  { symbol: "CRWD", name: "CrowdStrike Holdings Inc." },
  
  // Financials
  { symbol: "JPM", name: "JPMorgan Chase & Co." },
  { symbol: "BAC", name: "Bank of America Corporation" },
  { symbol: "WFC", name: "Wells Fargo & Company" },
  { symbol: "C", name: "Citigroup Inc." },
  { symbol: "GS", name: "Goldman Sachs Group Inc." },
  { symbol: "MS", name: "Morgan Stanley" },
  { symbol: "BLK", name: "BlackRock Inc." },
  { symbol: "SCHW", name: "Charles Schwab Corporation" },
  { symbol: "AXP", name: "American Express Company" },
  { symbol: "V", name: "Visa Inc." },
  { symbol: "MA", name: "Mastercard Incorporated" },
  { symbol: "PYPL", name: "PayPal Holdings Inc." },
  { symbol: "BRK-B", name: "Berkshire Hathaway Inc. Class B" },
  { symbol: "BRK-A", name: "Berkshire Hathaway Inc. Class A" },
  
  // Healthcare
  { symbol: "JNJ", name: "Johnson & Johnson" },
  { symbol: "UNH", name: "UnitedHealth Group Inc." },
  { symbol: "PFE", name: "Pfizer Inc." },
  { symbol: "ABBV", name: "AbbVie Inc." },
  { symbol: "TMO", name: "Thermo Fisher Scientific Inc." },
  { symbol: "ABT", name: "Abbott Laboratories" },
  { symbol: "MRK", name: "Merck & Co. Inc." },
  { symbol: "LLY", name: "Eli Lilly and Company" },
  { symbol: "DHR", name: "Danaher Corporation" },
  { symbol: "BMY", name: "Bristol-Myers Squibb Company" },
  { symbol: "AMGN", name: "Amgen Inc." },
  { symbol: "GILD", name: "Gilead Sciences Inc." },
  { symbol: "CVS", name: "CVS Health Corporation" },
  { symbol: "CI", name: "Cigna Corporation" },
  
  // Consumer & Retail
  { symbol: "WMT", name: "Walmart Inc." },
  { symbol: "HD", name: "Home Depot Inc." },
  { symbol: "COST", name: "Costco Wholesale Corporation" },
  { symbol: "MCD", name: "McDonald's Corporation" },
  { symbol: "NKE", name: "NIKE Inc." },
  { symbol: "SBUX", name: "Starbucks Corporation" },
  { symbol: "TGT", name: "Target Corporation" },
  { symbol: "LOW", name: "Lowe's Companies Inc." },
  { symbol: "DIS", name: "Walt Disney Company" },
  { symbol: "CMCSA", name: "Comcast Corporation" },
  { symbol: "PEP", name: "PepsiCo Inc." },
  { symbol: "KO", name: "Coca-Cola Company" },
  { symbol: "PG", name: "Procter & Gamble Company" },
  { symbol: "PM", name: "Philip Morris International" },
  { symbol: "MO", name: "Altria Group Inc." },
  
  // Energy
  { symbol: "XOM", name: "Exxon Mobil Corporation" },
  { symbol: "CVX", name: "Chevron Corporation" },
  { symbol: "COP", name: "ConocoPhillips" },
  { symbol: "SLB", name: "Schlumberger Limited" },
  { symbol: "EOG", name: "EOG Resources Inc." },
  { symbol: "MPC", name: "Marathon Petroleum Corporation" },
  { symbol: "PSX", name: "Phillips 66" },
  { symbol: "VLO", name: "Valero Energy Corporation" },
  
  // Industrials
  { symbol: "BA", name: "Boeing Company" },
  { symbol: "CAT", name: "Caterpillar Inc." },
  { symbol: "GE", name: "General Electric Company" },
  { symbol: "HON", name: "Honeywell International Inc." },
  { symbol: "UPS", name: "United Parcel Service Inc." },
  { symbol: "LMT", name: "Lockheed Martin Corporation" },
  { symbol: "RTX", name: "RTX Corporation" },
  { symbol: "DE", name: "Deere & Company" },
  { symbol: "MMM", name: "3M Company" },
  
  // Telecommunications
  { symbol: "T", name: "AT&T Inc." },
  { symbol: "VZ", name: "Verizon Communications Inc." },
  { symbol: "TMUS", name: "T-Mobile US Inc." },
  
  // Real Estate & Utilities
  { symbol: "AMT", name: "American Tower Corporation" },
  { symbol: "PLD", name: "Prologis Inc." },
  { symbol: "NEE", name: "NextEra Energy Inc." },
  { symbol: "DUK", name: "Duke Energy Corporation" },
  { symbol: "SO", name: "Southern Company" },
  
  // Other Notable Companies
  { symbol: "UBER", name: "Uber Technologies Inc." },
  { symbol: "ABNB", name: "Airbnb Inc." },
  { symbol: "SHOP", name: "Shopify Inc." },
  { symbol: "SQ", name: "Block Inc." },
  { symbol: "COIN", name: "Coinbase Global Inc." },
];
